[package]
name = "Dioxus-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.4.0"
dioxus-router = "0.4.1"
dioxus-web = "0.4.0"
wasm-bindgen = "0.2.85"
js-sys = "0.3.62"
web-sys = "0.3.64"